### ISSUE TITLE
drag option is not working at all

### ISSUE THREAD

**Issue by kaisercanvas** [FrDH/jQuery.mmenu#622] opened 2016-09-08 16:02 UTC
I am trying to enable the 'drag'-option for our mmenu. But it seems to do nothing and does not throw any errors/warnings (even with mmenu debugger enabled).

I have attached the example from the download folder (we have just added the drag option).

`	
<title>jQuery.mmenu demo</title>

		<link type="text/css" rel="stylesheet" href="css/demo.css" />
		<link type="text/css" rel="stylesheet" href="js/drag.css" />
		<link type="text/css" rel="stylesheet" href="../dist/css/jquery.mmenu.all.css" />

		<script type="text/javascript" src="http://code.jquery.com/jquery-2.2.0.js"></script>
		<script type="text/javascript" src="js/hammer.js"></script>
		<script type="text/javascript" src="../dist/js/jquery.mmenu.all.min.js"></script>
		<script type="text/javascript" src="js/drag.js"></script>
		<script type="text/javascript">
			$(function() {
				$('nav#menu').mmenu({
					extensions	: [ 'effect-slide-menu', 'shadow-page', 'shadow-panels' ],
            drag: {
              page: {
                open: true
              }
            },
					counters	: true,
					navbar 		: {
						title		: 'Advanced m123enu'
					},
					navbars		: [
						{
							position	: 'top',
							content		: [ 'searchfield' ]
						}, {
							position	: 'top',
							content		: [
								'prev',
								'title',
								'close'
							]
						}, {
							position	: 'bottom',
							content		: [
								'<a href="http://mmenu.frebsite.nl/wordpress-plugin.html" target="_blank">WordPress plugin</a>'
							]
						}
					]
				});
			});
		</script>
	</head>
	<body>
		<div id="page">
			<div class="header">
				<a href="#menu"></a>
				Demo
			</div>
			<div class="content">
				<p><strong>This is an advanced demo.</strong><br />
					Click the menu icon to open the menu.</p>
			</div>
			<nav id="menu">
				<ul>
					<li><a href="#">Home</a></li>
					<li><span>About us</span>
						<ul>
							<li><a href="#about/history">History</a></li>
							<li><span>The team</span>
								<ul>
									<li><a href="#about/team/management">Management</a></li>
									<li><a href="#about/team/sales">Sales</a></li>
									<li><a href="#about/team/development">Development</a></li>
								</ul>
							</li>
							<li><a href="#about/address">Our address</a></li>
						</ul>
					</li>
					<li><a href="#contact">Contact</a></li>
				</ul>
			</nav>
		</div>
	</body>
</html>`

**Comment by FrDH** [comment] 2016-09-09 13:24
What version of the plugin are you using? The options changed in version 5.7

**Comment by kaisercanvas** [comment] 2016-09-09 13:33
I am using the most recent version from the website:
`"version"		: "5.7.3",`

**Comment by FrDH** [comment] 2016-09-10 07:00
Sounds like that should work, is there an online example I could have a look at?

**Comment by FrDH** [comment] 2016-09-10 07:11
Anything special in "js/drag.js"?

**Comment by mammothca** [comment] 2016-09-11 09:00
Hello. I am having a similar issue. Drag works to close a panel, but does not work to open the menu. Mmenu v5.7.2, Hammer v2.0.8. Using all.min.js and all.css. Interested in a solution! The project is on my local machine, so no live website.

**Comment by kaisercanvas** [comment] 2016-09-13 09:43
Unfortunately, our project where we are using the slide function is not public at the moment. I am using the drag.js file from the folder  \jQuery.mmenu-master\dist\addons\drag\. I am still trying to build a jsfiddle although it is difficult to add libraries which are not coming from a CDN.

**Comment by FrDH** [comment] 2016-09-19 07:10
I just tested the drag add-on in my test environment (basically the "demo" files that come with the download) and it all seemed to work as intended.
I don't think there's much I can do w/o an online example.

**Comment by FrDH** [comment] 2016-10-05 08:50
If no online example is provided, I'm going to consider this issue to be resolved and close it.

**Closed** 2016-10-07 19:01 UTC
