### ISSUE TITLE
jQuery 1.11 + Iphone 5 = load error

### ISSUE THREAD

**Issue by peternovozhilov** [FrDH/jQuery.mmenu#803] opened 2017-10-04 00:36 UTC
I have such issue at mobile mmenu loading on safari browser at iPhone 5: Syntax error, unrecognized expression: .mm-vert.mm-opened. jQuery 1.11,1.12.4 (I can't use another version of jquery, update of jquery is not an option, because I need to test to many already working scripts for compatibility). Version of mmenu: jQuery mmenu v6.1.8. IOS 10.2.1. Safari 10.0

My code is:
`
$(window).load(function() {

            try {
                $menu = $("#mobile-menu").mmenu({
                    navbar: {
                        title: ""
                    }
                }, {
                    offCanvas: {
                        pageNodetype: "div",
                        pageSelector: "#wrap-page"
                    }
                });
            } catch(e){
                alert(e.name + ":" + e.message + "\n" + e.stack);
            }
}
 
`

And at the desktop I see the menu. All working good. Also it working good at the mobile chrome, mozilla emulator at the desktop. But it stack at the mobile browser on loading with this error.

**Comment by peternovozhilov** [comment] 2017-10-04 07:06
The exception is here:
`e.add(e.find("." + i.vertical + "." + i.opened).children("." + i.panel));`

**Comment by FrDH** [comment] 2017-10-10 19:51
That's odd, I haven't heard of this issue before and I can't think of a reason for an iPhone 5 to throw such an error while other browsers don't. 
Does the menu on mmenu.frebsite.nl have the same issue?

**Comment by FrDH** [comment] 2017-12-04 21:42
Is this issue still relevant? I could not reproduce it.

**Comment by FrDH** [comment] 2017-12-23 09:15
I'm closing this issue since it could not be reproduced.

**Closed by FrDH** 2017-12-23 09:15 UTC
Labels: can't reproduce
