### ISSUE TITLE
MMenu became unscrollable on mobile devices when slidingSubmenus is set to false

### ISSUE THREAD

**Issue by zyxus** [FrDH/jQuery.mmenu#761] opened 2017-07-03 12:50 UTC
Example of this problem is here: 

1. Here is menu with slidingSubmenus: false
[http://z-y-x.ru/mmenu/](http://z-y-x.ru/mmenu/)

2. and here the same page but with slidingSubmenus: true
[http://z-y-x.ru/mmenu/index2.html](http://z-y-x.ru/mmenu/index2.html)

When browsing on mobile devices (for me it's an Iphone SE, ipad) the first page menu doesn't scrolls.
I didn't find why it happens...

Can somebody help please to solve this problem?

Thanks.

**Comment by FrDH** [comment] 2017-07-04 08:51
Sounds odd, haven't heard about this issue before. I'll investigate what might be causing it.

**Comment by zyxus** [comment] 2017-07-04 09:27
Here is the demonstration of this problem. Video captured on iphone 5S. SE, 6S also checked...
[https://youtu.be/n956FU7nFrQ](https://youtu.be/n956FU7nFrQ)

**Comment by zyxus** [comment] 2017-07-04 14:17
You know, we've found that menu begins to scroll if class .mm-opened is added to #menu .mm-panels .mm-panel

We temporarily solve the problem by adding the line below to javascript on page:
`$('#leftmnunw .mm-panels .mm-panel').addClass('mm-opened');`

I know than itsn't a right way, but it works now and i hope that it will help you to find a realy fix ))

**Comment by samuells** [comment] 2017-07-05 09:31
The same problem on our pages - tried lot of css hacks, but nothing worked. I will try @zyxus temp fix.

**Comment by samuells** [comment] 2017-07-05 09:52
The fix from @zyxus does not help us.

**Comment by zyxus** [comment] 2017-07-05 11:01
@samuells maybe you need to specify your own menu id? On our page Mmenu has a #leftmnunw id.
Can your give a link to your page? Maybe i can help you too? ))

**Comment by samuells** [comment] 2017-07-05 11:41
@zyxus It is not a problem of id ;) I just added class "mm-opened" to all mm-panel's. You can try here - https://www---dev-54ta5gq-zveeigks3ypgc.eu.platform.sh/en

**Comment by FrDH** [comment] 2017-07-05 18:15
The issue is caused by the scrollbugfix add-on, it prevents unwanted scrolling behavior on touch-devices by only enabling scrolling in a panel that has the classname "mm-opened". This classname is added to a panel when it is opened, but apparently `slidingSubmenus: false` no longer adds the classname to the main panel.

I'll fix this issue shortly, but for now your solutions should work just as well.

**Comment by FrDH** [comment] 2017-08-12 16:30
Should be fixed in the latest version

**Closed** 2017-09-01 06:46 UTC
