### ISSUE TITLE
"Fixed" class cause wrong position

### ISSUE THREAD

**Issue by letlet** [FrDH/jQuery.mmenu#476] opened 2015-11-21 02:08 UTC
I have a fixed "open/close" button of mmenu at the left top, and added the "Fixed" class because fixed element dissapear when web page scrolled. All works fine in PC.
Then if I click  "open/close" button in mobile browser within a small screen ,the menu slide out, but the "open/close" remain the same place on top of the menu ,not slide with the right main content. 
So I think may be my custom css confict with mmenu, but same problem if I removed all the custom css.
If the "Fixed" class removed, "open/close" button will slide with the right main content(though dissapear when scrolled). 

jQuery.mmenu is latest version.

**Comment by FrDH** [comment] 2015-11-22 19:49
I can't think of a reason why it wouldn't work on mobile browsers only. What exactly do you mean with "mobile browser"? What browser on what OS on what device?

**Comment by letlet** [comment] 2015-11-29 04:17
In all mobile device ,including iOS,Android, even in chrome developer mode on PC.

**Comment by FrDH** [comment] 2015-11-29 19:28
Is there an online example? The fixed header on mmenu.frebsite.nl seems to be working as expected on desktop and mobile (iOS).

**Comment by FrDH** [comment] 2015-12-30 10:25
I've done some testing and the fixedElement add-on works as intended.
Is this issue still relevant? Otherwise I'm going to close it.

**Closed** 2016-01-04 18:56 UTC
