### ISSUE TITLE
Scrolling in Safari

### ISSUE THREAD

**Issue by iEve1** [FrDH/jQuery.mmenu#601] opened 2016-07-09 20:48 UTC
Scrolling does not work in Safari 9.1 browser on OS X El Captaino.

**Comment by kubik101** [comment] 2016-07-10 14:46
I noticed an issue with scrolling too in Safari 9.1.

Only seems to be an issue when you drill down into the longer menus (e.g. Add-Ons) and when the height of the browser is taller than then the first level menu (Home).

If you resize the height a little it fixes the issue on the longer menus (they scroll).

I hope my 2 cents helps.

=)

**Comment by FrDH** [comment] 2016-07-10 16:45
If the issue disappears after resizing the browser, my guess is it's a bug in the browser. Does the issue also disappear is you trigger the "resize" event instead of actually resizing the browser? If so, I guess you could trigger the "resize" event onDocumentReady, after the plugin fired. Or when the menu opens, using the API.

I'll see if I can reproduce the issue later on.

**Comment by kubik101** [comment] 2016-07-18 04:43
Is it something you can reproduce and try that method? My JS skills are not the best.
It’s worth resolving for many Safari users.
=)

Trent Turner  
www.kubikdesign.com.au

> ecommerce  > content management systems  > website design & construction  > website maintenance  > email marketing   > web hosting   > domain registration

**Comment by FrDH** [comment] 2016-08-16 08:25
````js
$(window).resize();
````

**Closed** 2016-10-03 09:24 UTC
