### ISSUE TITLE
Widescreen no longer functional in 5.6.2

### ISSUE THREAD

**Issue by tmetzger** [FrDH/jQuery.mmenu#541] opened 2016-03-16 23:22 UTC
I had widescreen working nicely with an older version, but I upgraded today to 5.6.2 and found that when the page loads, mmenu doesn't write the "mm-current mm-opened" classes into the menu, so it doesn't start opened. I have to click on my hamburger menu to open it, which works fine.

The widescreen CSS is present in the dist directory, but a grep of the javascript doesn't find any occurrence of the string "widescreen". So the extension it doesn't seem to be present at all, unless I'm missing something important here!

Perhaps this functionality changed? But I don't think so - I'm really looking for behavior very similar to what exists on the author's site: http://mmenu.frebsite.nl/

Hoping for a simple answer, but I can post this live if it helps. Here's my menu:
```
      // The menu
      var API = $('#groupanizer-menu')
        .mmenu({
          extensions: ["widescreen"],
          counters: true,
          dividers: {
            fixed: true
          },
          navbar: {
            title: 'mmenu'
          },
          setSelected: {
            parent: true
          }
        }).data( 'mmenu' );

      $('#hamburger')
        .on( 'click',
          function( e )
          {
            e.preventDefault();
            if ( $html.hasClass( 'mm-opened' ) )
            {
              API.close();
            }
            else
            {
              API.open();
            }
          }
        );

```

**Comment by tmetzger** [comment] 2016-03-17 19:57
I was able to get the functionality I needed by setting the classes myself. Code follows:
`      var widescreen = function() {
        if( $(window).width() > 1200 && !$html.hasClass('mm-opened') ) {
          $html.addClass('mm-opened mm-blocking mm-background mm-widescreen mm-opening');
          $('#groupanizer-menu').addClass('mm-current mm-opened');
        } else if( $(window).width() < 1200 && $html.hasClass('mm-opened') ) {
          $html.removeClass('mm-opened mm-blocking mm-background mm-widescreen mm-opening');
          $('#groupanizer-menu').removeClass('mm-current mm-opened');
        }
      }
      // once on open
      widescreen();
      // and whenever the screen changes size
      $(window).resize( function() { widescreen() } );
`

So perhaps something like that code used to exist in the module?

**Comment by FrDH** [comment] 2016-03-17 21:56
In earlier versions, the widescreen extension always opened the last menu that was added to the page. In newer versions, you need to add "widescreen" to the `extensions` option:
````javascript
$("#menu").mmenu({
    extensions: ["widescreen"]
});
````
The widescreen.css file is not included in the .all.css file (otherwise the page would always be pushed out to the right, even if you wouldn't use the widescreen extensions). Therefor you need to include it separately (possibly using a media-query):
````css
<link href="path/to/widescreen.css" media="all and (min-width: 900px)" />
````

That should be all you need to do (no need for extra JS).
This is all [documented](http://mmenu.frebsite.nl/documentation/extensions/widescreen.html).

**Comment by tmetzger** [comment] 2016-03-17 22:11
Hi Fred,

I swear I've been up and down the documentation. I did see all the things
you have referenced.

So I did have 'widescreen' listed as an extension. Nonetheless, it wasn't
responding to changes in screen width. I don't know why. I did get it
working by writing those classes into the right places myself.

T

Tom Metzger, CEO
www.groupanizer.com
Facebook <http://www.facebook.com/groupanizer> | Twitter
<http://www.twitter.com/groupanizer>
Direct +1 604.451-7447

Groupanizer: +1 604.451.7464
North America Toll Free: 866.436.6565 x101

**Comment by FrDH** [comment] 2016-03-17 22:19
As you can see on the website, the widescreen extensions working as intended. So without an online example there's not much I can do for you.

**Comment by FrDH** [comment] 2016-03-19 10:02
I had a look at the website, and think it has to do with the loading order. The widescreen.css file (apparently) is requred to be added AFTER the .all.css file.

In your case, the css for the offCanvas add-on overrides the css for the widescreen extension:
````css
.mmenu.mm-widescreen {
    display: block;
}
.mm-menu.mm-offcanvas {
   display: none;
}
````
An easy fix for this would be to add `!important` to the `display: block`:
````css
.mm-menu.mm-widescreen {
   display: block !important;
}
````

I'll add this in the next version, for now you should add it manuall.

**Comment by tmetzger** [comment] 2016-03-19 21:01
Aha! Yes that worked nicely - thanks.

The menu is really looking sharp! I have the search implemented now, which
is super.

Couple of questions, if you don't mind:

   - The menu doesn't display until the page has loaded, to avoid looking
   at the unformatted code until the javascript runs. This of course makes the
   menu flash every time one loads a page, when in widescreen. Is there
   anything clever I can do to minimize this? Your site doesn't seem to suffer
   from this issue.


   - Your site seems to have implemented the third-party "currentItem"
   addon. At least for most menu items, your site correctly finds the current
   page in the menu. I've got that loading (after the rest of the code!), and
   configure with { find: true }, but it doesn't seem to be doing anything. I
   realize it's not your code. Nonetheless, any tips?

BTW, happy to have these conversations on github instead!

Tom

Tom Metzger, CEO
www.groupanizer.com
Facebook <http://www.facebook.com/groupanizer> | Twitter
<http://www.twitter.com/groupanizer>
Direct +1 604.451-7447

Groupanizer: +1 604.451.7464
North America Toll Free: 866.436.6565 x101

**Comment by FrDH** [comment] 2016-04-02 21:44
Sorry for the late reply.

1) You can use CSS to hide a menu when until the plugin loads: http://mmenu.frebsite.nl/support/tips-and-tricks.html

2) My site just adds the class "Selected" to the LI for the current page. As suggested in [this tutorial](http://mmenu.frebsite.nl/tutorials/off-canvas/styling-lists.html). Note that this classname can be configured as it probably is different per CMS (Magento uses "active", WP uses "current-menu-page", etc.).
The third party add-on should be able to find the correct menu item based on the URL. But I'd recommend just adding the "Selected" class to the LI.

Hope this helps.

**Closed** 2016-04-19 07:55 UTC
