### ISSUE TITLE
Menu stops scrolling when orientation is changed

### ISSUE THREAD

**Issue by davidenco** [FrDH/jQuery.mmenu#821] opened 2017-11-10 12:54 UTC
On my iPhone 6 with iOS 11.1.1 using version 6.1.8.

TEST 1:
Starting in portrait mode, I am opening the menu and then rotating the device into landscape mode. When I try to scroll the menu, the main content scrolls instead and the menu remains unchanged.

TEST 2:
If I start in landscape mode and open the menu, I can scroll the menu and the main content remains unchanged. Rotate the device into portrait and then back into landscape mode, now the menu is no longer scrollable but the main content is.

**Comment by FrDH** [comment] 2017-11-10 16:39
What version of the plugin are you using? The current version includes the "scrollBugFix" add-on by default. This add-on should solve all unwanted scrolling issues.

**Comment by davidenco** [comment] 2017-11-10 16:44
Latest version - 6.1.8.

I assume I am applying it correctly?

$("#mmenu").mmenu({
        offCanvas: {
            position : 'right',
            zposition: 'front'
        },
        scrollBugFix: {
            fix: true
        },
        extensions: [
            'theme-dark',
            'fx-listitems-fade',
            'listview-large',
            'border-full',
            'shadow-page'
        ]
    });

If so, it doesn't work. I can see a scroll bar on the iPhone which moves up/down but the menu itself does not unless the menu is closed and reopened.

**Comment by FrDH** [comment] 2017-11-11 08:44
Yes, that's how it should work. I'll investigate the issue later on.

p.s. `scrollBugFix.fix: true` is the default setting, so you do not need to set it.

**Comment by FrDH** [comment] 2017-11-13 17:26
Hmm, I could not reproduce the issue on my iphone7 (iOS 11.1.1) and currently do not have access to an iphone6. Do you see this issue on the menu on menu.frebsite.nl ?

**Comment by FrDH** [comment] 2017-12-23 09:18
Is this issue still relevant? Otherwise I'm going to close it since I could not reproduce it.

**Closed** 2018-03-02 10:31 UTC
Labels: can't reproduce
