### ISSUE TITLE
Sub items of parent siblings are visible if lazy submenu addon is enabled

### ISSUE THREAD

**Issue by Patta** [FrDH/jQuery.mmenu#782] opened 2017-08-14 12:41 UTC
With lazy submenu addon, the sub items of the parent siblings are visible in opened menu.
Example on screenshot: if panel with item 1 - 4 is open, the sub items of the parent items (grey numbers) are visible. Without lazy submenu addon everything is ok. 

![bug_lazymenus](https://user-images.githubusercontent.com/2151127/29271921-25a00a7c-80fe-11e7-8225-86ac438044bb.png)
(i renamed the pages)

Maybe some styles are missing?

**Comment by FrDH** [comment] 2017-08-15 14:15
Hi, thanks for bringing this to my attention.
I don't think the lazySubmenus add-on has been tested in combination with the iconPanels add-on.
I'll see if I can fix this shortly.

**Comment by FrDH** [comment] 2017-11-11 18:04
I tried but could not reproduce the issue, what version of the plugin are you using?

**Comment by Patta** [comment] 2017-11-14 11:44
in v6.1.8 this bug still exist

**Comment by FrDH** [comment] 2017-12-23 09:14
Could you set up an online example of the issue? I can't seem to reproduce it.

**Comment by Patta** [comment] 2018-01-08 15:44
currently not, sorry. issue still in 7.0.0

**Comment by FrDH** [comment] 2018-03-02 10:31
Closing this issue due to lack of an online example. Please create a new issue if any further help is needed.

**Closed by FrDH** 2018-03-02 10:31 UTC
Labels: bug, can't reproduce
