### ISSUE TITLE
ScrollTop on mobile search input

### ISSUE THREAD

**Issue by matass** [FrDH/jQuery.mmenu#664] opened 2016-11-29 08:56 UTC
First of all - Thanks for the great plug! 

there is a bug on iOS. when I scroll down to the page  and click on menu burger - everything works fine and mmenu shows up. But when I click on mm-search input field page content scrolls to the top.

**Comment by FrDH** [comment] 2016-11-29 10:16
This issue is probably caused by iOS trying to position the input field above the virtual keyboard, not realizing the input field is in a fixed positioned element.

You could try to prevent the page from scrolling while the input field has focus, but my guess is iOS won't respect that:
````js
$("html, body").on( "scroll", function( e ) {
    if ( $(".mm-search input").filter( ":focus" ).length )
    {
        e.preventDefault();
        e.stopImmediatePropagation();
    }
});
````

Let me know how that works out.

**Comment by FrDH** [comment] 2017-01-17 08:38
@MatasSim did you get a change to test the suggested fix?

**Comment by MatasSim** [comment] 2017-01-17 10:28
@FrDH I've tested with iOS simulator. here`s a video: 
https://vimeo.com/199799750

I'll try to find a fix for this issue

**Comment by FrDH** [comment] 2017-01-17 11:35
Try this:
http://stackoverflow.com/questions/2952782/preventing-an-input-element-from-scrolling-the-screen-on-iphone

**Comment by FrDH** [comment] 2017-02-25 14:11
@matass did you find a sollution in the suggested stackoverflow page?

**Comment by matass** [comment] 2017-02-25 16:35
@FrDH as I remember your solution is not working. Right now I have some free time and I will try to find a sollution.

**Comment by FrDH** [comment] 2017-06-30 11:01
I tried Safari, FireFox and Chrome (o iOS), but could not fully reproduce the issue. On focussing the input, the page scrolled up about the height of the keyboard. I don't think there is much I can do about that as it is build-in browser behavior.

**Closed by FrDH** 2017-06-30 11:01 UTC
Labels: enhancement
