### ISSUE TITLE
Bug website - v6.0.0 Uncaught ReferenceError: msg is not defined

### ISSUE THREAD

**Issue by Quentame** [FrDH/jQuery.mmenu#713] opened 2017-03-23 12:39 UTC
Hi !

### Description
I've notice in [jQuery.mmenu website](http://mmenu.frebsite.nl/) that all playgrounds don't work, in all browsers.

The menu don't open when I scroll close to it **and** toogles haven't any effects on the playground and on the code sandboxed sample.

A JavaScript error happens

```javascript
Uncaught ReferenceError: msg is not defined
    at Object.warn (http://mmenu.frebsite.nl/demo/index.html?demo=playground&menu=default:31:13)
    at deprc (http://mmenu.frebsite.nl/mmenu/jquery.mmenu.debugger.js?v=5.7.1:45:8)
    at e.(anonymous function).$.(anonymous function).___deprecated (http://mmenu.frebsite.nl/mmenu/jquery.mmenu.debugger.js?v=5.7.1:75:5)
    at e.(anonymous function) (http://mmenu.frebsite.nl/mmenu/js/jquery.mmenu.all.min.js?v=5.7.1:13:1076)
    at HTMLElement.<anonymous> (http://mmenu.frebsite.nl/mmenu/js/jquery.mmenu.all.min.js?v=5.7.1:13:10012)
    at Function.each (https://code.jquery.com/jquery-1.12.4.min.js:2:2881)
    at n.fn.init.each (https://code.jquery.com/jquery-1.12.4.min.js:2:846)
    at n.fn.init.e.fn.(anonymous function) [as mmenu] (http://mmenu.frebsite.nl/mmenu/js/jquery.mmenu.all.min.js?v=5.7.1:13:9961)
    at createMenu (http://mmenu.frebsite.nl/demo/index.html?demo=playground&menu=default:112:20)
    at updateMenu (http://mmenu.frebsite.nl/demo/index.html?demo=playground&menu=default:144:8)
```

I haven't updated the plugin into one of my projects, so I still don't know if this is showcase specific.

### Test case
- Go on [jQuery.mmenu website](http://mmenu.frebsite.nl/)
- Go on examples or any extensions/add-ons page
- Check the playground, also called "Example"

### Test environment
- Safari 9 Mas OS 10.9
- Edge 14 Win10
- Firefox 54 Win10
- Chrome 57 Win10

---

[Examples](http://mmenu.frebsite.nl/examples.html) are still working but they are not updated to v6.0.0. So they should be updated too and it will permit to check if there is regression or not.

Also I could check if the issue #663 (Safari issue Mac OS & iOS) has been solved or if I have to review my PR #710 (Fix Safari justifiedlistview item height).

I think we have to include those examples (even more) into the git (using local resources of course) to provide a test environment and to check the non regression of future builds. I can create a pull request.

### Screenshot
![jQuery.mmenu v6.0.0-js-bug](https://cloud.githubusercontent.com/assets/14821482/24246769/3ae7e590-0fc9-11e7-9f3f-8593d78baab7.png)

See you soon !

**Comment by FrDH** [comment] 2017-03-23 21:34
Sorry about that, forgot the demos were cached :/
Basically all demos should work now, although I noticed a small issue on the playground page.

**Comment by Quentame** [comment] 2017-03-23 22:37
Okeyyyy, it seems to work fine now 😉
Thanks !

**Comment by DaveyJake** [comment] 2017-03-28 15:59
Not sure if this is related but when viewing on Chrome for MacOS Sierra, the demos aren't working.  When viewing the DOM inside of Chrome DevTools, here's what I'm seeing:

<img width="1026" alt="screen shot 2017-03-28 at 9 54 48 am" src="https://cloud.githubusercontent.com/assets/826532/24414961/20035a7a-139d-11e7-891e-478c278dfab8.png">

<img width="1158" alt="screen shot 2017-03-28 at 9 56 45 am" src="https://cloud.githubusercontent.com/assets/826532/24414967/2478f470-139d-11e7-83ed-3d93c914a3e3.png">

Any ideas what the main areas would be off alignment like this?

**Comment by FrDH** [comment] 2017-03-28 20:13
The demo's were cached, the cache is removed and the demos should work fine now.
I tested the demo's on Chrome for MacOS El Capitan and they seem to work as intended. I can't tell you why the debugger is off alignment, but it probably has something to do with the examples being in an iframe.

**Comment by Quentame** [comment] 2017-03-28 21:02
@FrDH did you fixed the "small issue on the playground page" you noticed ?

**Comment by FrDH** [comment] 2017-03-29 14:52
not yet :/

**Comment by FrDH** [comment] 2017-03-29 18:27
should be fixed now

**Closed** 2017-03-31 11:21 UTC
