### ISSUE TITLE
Close menu after click

### ISSUE THREAD

**Issue by eduardobelchior** [FrDH/jQuery.mmenu#880] opened 2018-04-14 11:54 UTC
How can I close the menu just after clicking one of the options? I'm using v5.6.5

**Comment by FrDH** [comment] 2018-04-16 10:49
Try setting the `close.onClick` option to `true`:
http://mmenu.frebsite.nl/documentation/core/options.html

**Comment by eduardobelchior** [comment] 2018-04-16 16:34
don't work

`$("#primary-navigation").mmenu({
        extensions: ['effect-slide-menu', 'pageshadow'],
        navbar: {
            title: 'MENU'
        },
        onClick: {
            close: true
        },
        navbars: [
            {
                position: 'top',
                content: [
                    'prev',
                    'title',
                    'close'
                ]
            }
        ]
    }, {
        // configuration
        clone: true
    });`

**Comment by FrDH** [comment] 2018-04-21 09:33
I think that should work :| 
Is there an online example I could have a look at?

**Comment by FrDH** [comment] 2018-06-03 09:16
Without an online example, I'm going to close this issue as I can't reproduce it.

**Closed by FrDH** 2018-06-03 09:16 UTC
